import React, { useEffect } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Script from 'next/script';
import Video from '../components/Video';

export default function Home() {
  useEffect(()=>{
    Video(document)
  }, [])
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="hero">
          <canvas id="hero-lightpass"/>
        </div>
        <div className="intro">
          <h1>The New Dev Ed Pro</h1>
          <video src="/video/Apple-Dev Ed Pro.mp4"></video>
        </div>
        <section>
          <h1>REVOLUTIONARRY</h1>
        </section>
      </main>
      <Script src="/js/script.js"></Script>
    </div>
  )
}
